service: serverlessBoilerplate

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

# functions
functions:
  hello:
    handler: src/app.lambdaHandler
    events: # The events that trigger this function
      - http: 
          path: serverlessBoilerplate/hello
          method: get
 
# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
